/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bhaweshkumar;

import com.bhaweshkumar.list.LinkedList;

public class App {
    public static void main(String[] args) {
        LinkedList<String> simpleList = new LinkedList<>();
        simpleList.addLast("Bhawesh");
        simpleList.addLast("kumar");
        simpleList.printNodes();
    }
}
